name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    environment: MONGO_URI

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Env Secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "MONGO_URI is set: ${MONGO_URI:+yes}"
          echo "JWT_SECRET is set: ${JWT_SECRET:+yes}"
          echo "PORT is set: ${PORT:+yes}"

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
